version: '3'

services:
  api:
    build:
      context: "."
      dockerfile: Dockerfile
    container_name: "FastApi"
    network_mode: host
    #command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:000"
    command: bash -c "uvicorn main:app --reload"
    depends_on:
      - postgresql

  postgresql:
    image: postgres
    container_name: "postgresql"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_DB=blog
    ports:
      - "5432:5432"
    volumes:
      - postgresql:/var/lib/postgresql/data
volumes:
  postgresql:
    driver: local
