version: '3.7'

services:
  api:
    build:
      context: "."
      dockerfile: Dockerfile
    container_name: "FastApi"
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/
    ports:
      - "8000:8000"
    depends_on:
      - postgresql

  postgresql:
    image: postgres
    container_name: "postgresql"
    volumes:
      - postgresql_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
volumes:
  postgresql_data: